using Godot;
using System;

/*
 * Bot (BotMove class):
 * 
 * This class contains the algorithms required to generate bot moves for various difficulties
 * and communicates with the main gameplay (the Center class) to decide on a final bot move
 */
public partial class BotMove : Node2D
{
    /*
     * Custom signals:
     * -> EndRound: ends the round (and possibly the tournament)
     * -> SendBotMoves: send the final bot move back to Center
     */
    [Signal] public delegate void EndRoundEventHandler();
    [Signal] public delegate void SendBotMovesEventHandler(int botMove);

    
    public enum Move { ROCK = 0, PAPER = 1, SCISSORS = 2};

    // Loading image
    private static Texture2D _rockImage = GD.Load<Texture2D>("res://assets/textures/rock.png");
    private static Texture2D _paperImage = GD.Load<Texture2D>("res://assets/textures/paper.png");       
    private static Texture2D _scissorsImage = GD.Load<Texture2D>("res://assets/textures/scissors.svg");
    
    // Creating image textures from images
    private static ImageTexture _rockTexture = ImageTexture.CreateFromImage(_rockImage.GetImage()); 
    private static ImageTexture _paperTexture = ImageTexture.CreateFromImage(_paperImage.GetImage()); 
    private static ImageTexture _scissorsTexture = ImageTexture.CreateFromImage(_scissorsImage.GetImage());

    /*
     * Private static variables:
     * -> _playerRound1Moves and _botRound1Moves store the initial 2 player and bot moves
     * -> _difficulty stores the bot difficulty in the tournament
     */
    private static int[] _playerRound1Moves = new int[2];
    private static int[] _botRound1Moves;
    private static string _difficulty = "Easy";
    private static int EASY_HARD_SPLIT_CHANCE = 20;

    private MoveHelper _moveHelper;

    //...
    [Export] private NodePath _display1Path;
    [Export] private NodePath _display2Path;

    private Sprite2D _display1;
    private Sprite2D _display2;


    // Initialization function 
    public override void _Ready()
    {
        _display1 = GetNode<Sprite2D>(_display1Path);
        _display2 = GetNode<Sprite2D>(_display2Path);
    }

    public void SetMoveHelper(MoveHelper helper)
    {
        _moveHelper = helper;
    }

    // helper functions for readability

    /*
     * In C#, a pseudorandom unsigned integer is generated by creating a Random object and
     * calling .Next(..., ...)
     * Bot move generation
     */
    private int[] GenerateBotRound1Moves()
    {
        Random rng = new Random();
        if (_difficulty.Equals("Easy") || (_difficulty.Equals("Medium") && rng.Next(0, 100) < EASY_HARD_SPLIT_CHANCE))
        {
            return new int[] { rng.Next(3), rng.Next(3) };
        }

        int baseMove = rng.Next(3);
        return new int[] { baseMove, (baseMove + 1) % 3};
    }

    //......
    private int GenerateRemoveChoice()
    {
        Random rng = new Random();

        if (_difficulty.Equals("Easy") || (_difficulty.Equals("Medium") && rng.Next(0, 100) < EASY_HARD_SPLIT_CHANCE))
        {
            return rng.Next(0, 2);
        }
        // May be subject to change, since NE is only round-based instead of tournament-based
        else
        {
            if (_botRound1Moves[0] == _botRound1Moves[1])
            {
                return 0;
            }

            int temp = _botRound1Moves[0];
            int mixedStrategy = rng.Next(0, 3);
            if ((_playerRound1Moves[0] == temp && _playerRound1Moves[1] == temp) ||
                (_playerRound1Moves[0] == (temp + 1) % 3 && _playerRound1Moves[1] == (temp + 1) % 3) ||
                (_playerRound1Moves[0] == temp && _playerRound1Moves[1] == (temp + 1) % 3) ||
                (_playerRound1Moves[0] == (temp + 1) % 3 && _playerRound1Moves[1] == temp))
            {
                return 0;
            }
            else if (_playerRound1Moves[0] == (temp + 2) % 3 && _playerRound1Moves[1] == (temp + 2) % 3)
            {
                return 1;
            }
            else if (_playerRound1Moves[0] == temp && _playerRound1Moves[1] == (temp + 2) % 3 ||
                        _playerRound1Moves[0] == (temp + 2) % 3 && _playerRound1Moves[1] == temp)
            {
                if (mixedStrategy == 0)
                {
                    return 0;
                }
                else
                {
                    return 1;
                }
            }
            else
            {
                if (mixedStrategy == 0)
                {
                    return 1;
                }
                else
                {
                    return 0;
                }
            }
        }
    }

    //...
    private void UpdateDisplayTexture(int move, Sprite2D display)
    {
        if (move == (int)Move.ROCK) 
        {
            display.SetTexture(_rockTexture);
        }
        else if (move == (int)Move.PAPER) 
        {
            display.SetTexture(_paperTexture);
        }
        else
        {
            display.SetTexture(_scissorsTexture);
        }
    }

    /*
     * Connected to a signal in the Center class
     *
     * Transfer the difficulty data from the Center class and store it in 
     * this class (in _difficulty)
     */ 
    private void OnSetDifficulty(string difficulty)
    {
        _difficulty = difficulty;
    }

    /*
     * Confirm player's 2 stage 1 moves
     * 
     * Checks if the player chooses move for both hands. 
     * -> Yes:
     *    -> Disable and hide RPS choice button
     *    -> Generate bot moves depending on the difficulty
     *       -> Easy: random moves (makes each decision with equal probabilities) 
     *       -> Hard: Optimal play according to Nash Equilibrium
     *       -> Medium: A mixed strategy of easy mode (20% of the time) and hard mode 
     *          (80% of the time) in each round
     *    -> Show the chosen bot moves in the display
     *    -> Store the 2 initial bot moves in the class (in _botRound1Moves)
     * -> No: A warning label will show up (coded in the Center class)
     *
     */
    private void OnConfirmMoveButtonPressed() 
    {
        if (!IsInsideTree())
        {
            return;
        }

        if (_moveHelper.HasPlayerMadeAllMoves())
        {
            // Abstract bot logic into methods or even classes
            _botRound1Moves = GenerateBotRound1Moves();
            
            UpdateDisplayTexture(_botRound1Moves[0], _display1);
            UpdateDisplayTexture(_botRound1Moves[1], _display2);
        }
    }

    /*
     * Finalize the player moves and generate a final bot move 
     * 
     * Check if the player has chosen a hand to remove
     * -> Yes:
     *    -> Disable and hide RPS choice button ...
     *    -> Generate bot moves depending on the difficulty
     *       -> Easy: Random
     *       -> Hard: Optimal play according to Nash Equilibrium
     *       -> Medium: A mixed strategy of easy mode (20% of the time) and hard mode 
     *          (80% of the time) in each round
     *    -> Hide the display corresponding to the removed hand
     *    -> Send the final bot move back to the Center class
     * -> No: A warning label will show up (coded in Center)
     */
    private void OnRemoveHandButtonPressed()
    {
        if (!IsInsideTree())
        {
            return;
        }

        // Abstract bot logic into methods or even classes
        if (_moveHelper.HasPlayerChosenRemove())
        {
            int removeChoice = GenerateRemoveChoice();

            if (removeChoice == 0) 
            {
                // First hand removed
                _display1.SetVisible(false);
                _display2.SetVisible(true);
                EmitSignal(SignalName.SendBotMoves, _botRound1Moves[1]);
            }
            else
            {
                // Second hand removed
                _display1.SetVisible(true);
                _display2.SetVisible(false);
                EmitSignal(SignalName.SendBotMoves, _botRound1Moves[0]);
            }

            EmitSignal(SignalName.EndRound);
        }
    }

    /*
     * Connected to a signal in the Center class
     *
     * Transfer the data for the 2 initial player moves (that the bot use to decide which hand to 
     * remove in stage 2) from Center to this class (in _playerRound1Moves)
     */
    private void OnSendPlayerMoves(int[] arr)
    {
        _playerRound1Moves = arr;
    }
}
